//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallToTheHallOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HallToTheHallOwner()
        {
            this.HallPriceLists = new HashSet<HallPriceList>();
            this.JoysOwnerHalls = new HashSet<JoysOwnerHall>();
        }
    
        public int Hall { get; set; }
        public int Owners { get; set; }
        public string LocationHall { get; set; }
        public int MaximumNumberOfPlaces { get; set; }
        public int Stars { get; set; }
        public int MinimumPlacesToBook { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public Nullable<bool> IsAccessibilityLevel { get; set; }
        public Nullable<bool> IsParking { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string HallName { get; set; }
        public string Remarks { get; set; }
        public string Kashrut { get; set; }
    
        public virtual HallOwner HallOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HallPriceList> HallPriceLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoysOwnerHall> JoysOwnerHalls { get; set; }
    }
}
