//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallPriceList
    {
        public int PriceList { get; set; }
        public int Owners { get; set; }
        public int Hall { get; set; }
        public int Joy { get; set; }
        public string BasePrice { get; set; }
        public string Popularity { get; set; }
    
        public virtual HallOwner HallOwner { get; set; }
        public virtual HallToTheHallOwner HallToTheHallOwner { get; set; }
        public virtual Joy Joy1 { get; set; }
    }
}
