//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoysOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JoysOwner()
        {
            this.JoysOwnerHalls = new HashSet<JoysOwnerHall>();
        }
    
        public int JoyOwner { get; set; }
        public string NameOwnerJoy { get; set; }
        public string EmailOwnerJoys { get; set; }
        public string PasswordOwnerJoys { get; set; }
        public string IDOwnerJoys { get; set; }
        public string PhoneJoysOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoysOwnerHall> JoysOwnerHalls { get; set; }
    }
}
