//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoysOwnerHall
    {
        public int JoyOwnerHall { get; set; }
        public int Joy { get; set; }
        public int Owners { get; set; }
        public Nullable<System.DateTime> SearchBaseDate { get; set; }
        public Nullable<System.DateTime> SearchCeilingDate { get; set; }
        public Nullable<int> SeveralPlaces { get; set; }
        public Nullable<bool> IsAccessibilityLevel { get; set; }
        public Nullable<bool> IsParking { get; set; }
        public Nullable<System.DateTime> PlacementDate { get; set; }
        public int Hall { get; set; }
        public Nullable<int> CeilingPrice { get; set; }
        public string ChatanName { get; set; }
        public string CalaName { get; set; }
        public string Seminar { get; set; }
        public string YeshivaName { get; set; }
    
        public virtual HallToTheHallOwner HallToTheHallOwner { get; set; }
        public virtual Joy Joy1 { get; set; }
        public virtual JoysOwner JoysOwner { get; set; }
    }
}
